name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci || {
            echo "npm install failed. Showing npm debug log:"
            cat npm-debug.log
            exit 1
          }

      - name: Run ESLint
        run: |
          echo "Running ESLint..."
          npm run lint || {
            echo "ESLint failed. Showing detailed errors:"
            npm run lint -- --debug
            exit 1
          }

      - name: Type check
        run: |
          echo "Running TypeScript type check..."
          npm run type-check || {
            echo "TypeScript type check failed."
            exit 1
          }

      - name: Build
        run: |
          echo "Building project..."
          npm run build || {
            echo "Build failed. Showing build logs:"
            exit 1
          }

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
